### ISSUE TITLE
specify a channel

### ISSUE THREAD

**Issue by infinite-Joy** [flawcode/website#4]
we need to decide on a channel where we can discuss about this, maybe some channel on slack, Because I have some ideas about it but I dont knor much about javascript hence would need a lot of help.

**Comment by roughcoding** [comment]
Yeah, Sure. Whatsapp group would do?

**Comment by infinite-Joy** [comment]
I think so. But sherin is not reachable on whatsapp right now. isnt it?

Regards
Joydeep Bhattacharjee
phone 8981849869
mailto: joydeepubuntu@gmail.com
linkedinID: in.linkedin.com/pub/joydeep-bhattacharjee/57/a11/934/
blog: joydeepbhatt.com
Github: https://github.com/infinite-Joy
http://in.linkedin.com/pub/joydeep-bhattacharjee/57/a11/934/

**Comment by infinite-Joy** [comment]
This is resolved
